### PR TITLE
Extracting Station into an interface

### PR DESCRIPTION
**Pull request by SleimanJneidi**
I've extracted Station into an interface, this should make it more flexible for reasons that you certainly know :). Renamed the constant to Stations (it is the norm). I will might start adding tests once I understand what the project does :)

### CODE REVIEW

**Comment by SleimanJneidi** [comment]
Hi Stephen, do you want to add unit testing to the project?

**Comment by jodastephen** [comment]
So, the project fulfils my original goal of calculating numbers for the Crossrail 2 consultation. A few sanity check unit tests would be a good idea to make sure that the numbers are not crazy. If the project were to be extended to cover many more routes and stations it would need a lot more doing, but I wasn't planning on extending it further. What was your interest here?

**Comment by SleimanJneidi** [comment]
I am interested in converting quadratic algorithms into linear ones (#Model.solve) just for the fun of doing it:) but because there is no testing I can't validate my improvements.

**Comment by jodastephen** [comment]
So, one way to validate it is to run the class `Crossrail2ModelRunner`. That writes out all the output files. If the output files do not change (check with git), then your changes are successful. (Its a kind of indirect testing - the output files are checked and can be used to validate what effect any changes have)

**Comment by SleimanJneidi** [comment]
So are you sure that the numbers produced by the current algorithm are correct? Are you interested in such an improvement? In other words, if I am faced with something that I don't fundamentally understand, do you mind being nagged :) ?

**Comment by jodastephen** [comment]
I can be nagged, although sometimes my response to emails gets delayed. If you find bugs, then they should be fixed!

**Pull request merged**
